### ISSUE TITLE
Combine the two py files

### ISSUE THREAD

**Issue by samteaf** [rlanman14/assignment-3#15]
The two py files that need to combined are the two that answer the two questions. The 6 month one and the total one.

**Comment by samteaf** [comment]
To see the combination code go to my new branch samteaf-patch-1 then go to my sam.py file to see the combination. I didn't want to commit it Main just yet.

**Comment by mjwalts** [comment]
I copied your code into a new file to test some things out, and I added two lines under the increment line. It seems to work that way..but am not sure if that is the best way to do it lol 


if start_date <= log_date <= end_date:
        total_requests_in_6_months += 1  # Increment the count if it falls within the period

# Decrement the count by 1 after the loop
total_requests_in_6_months -= 1

**Comment by mjwalts** [comment]
omg idk why it did that 


# Decrement the count by 1 after the loop
total_requests_in_6_months -= 1

**Comment by mjwalts** [comment]
( # Decrement the count by 1 after the loop )
total_requests_in_6_months -= 1

idk why its doing that with the first line but just that line w/o the parenthesis

**Comment by mjwalts** [comment]
I fixed it on your branch but did not pull it to main yet, we can do it tomorrow! :D

**Comment by samteaf** [comment]
That's amazing that you found the fix for that! I tested everything on my end and it seemed to work

**Comment by rlanman14** [comment]
tested again successfully, merged branch into main
